"""Provider- and adapter-independent domain types."""

from revanent.domain.errors import (
    ApprovalGateError,
    DomainError,
    InvalidIdentifierError,
    InvalidTransitionError,
)
from revanent.domain.identifiers import (
    AgentAttemptId,
    AgentInvocationId,
    EventId,
    RunId,
    TaskId,
    WorkPackageId,
)
from revanent.domain.models import (
    ApprovalGate,
    AttemptCounterKind,
    AttemptCounters,
    BudgetLimits,
    FindingSeverity,
    ReviewFinding,
    ReviewResult,
    ReviewVerdict,
    Run,
    RunEvent,
    RunEventType,
    RunState,
    StateTransition,
    TaskSpecification,
    TransitionMetadata,
    TransitionResult,
    WorkPackage,
    WorkPackageStatus,
)
from revanent.domain.state_machine import (
    permitted_destinations,
    transition_run,
)

__all__ = [
    "AgentAttemptId",
    "AgentInvocationId",
    "ApprovalGate",
    "ApprovalGateError",
    "AttemptCounterKind",
    "AttemptCounters",
    "BudgetLimits",
    "DomainError",
    "EventId",
    "FindingSeverity",
    "InvalidIdentifierError",
    "InvalidTransitionError",
    "ReviewFinding",
    "ReviewResult",
    "ReviewVerdict",
    "Run",
    "RunEvent",
    "RunEventType",
    "RunId",
    "RunState",
    "StateTransition",
    "TaskId",
    "TaskSpecification",
    "TransitionMetadata",
    "TransitionResult",
    "WorkPackage",
    "WorkPackageId",
    "WorkPackageStatus",
    "permitted_destinations",
    "transition_run",
]
